In [1]:
!pip3 install pandas
!pip3 install sklearn
!pip3 install tqdm

In [1]:
#coding=utf-8
import csv
import os
import numpy as np
import pandas as pd
import jieba
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import mutual_info_classif
from tqdm import tqdm
from collections import Counter
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer


In [5]:
def stopwordslist():
    stopwords = [line.strip() for line in open('null.txt', encoding='UTF-8').readlines()]
    return stopwords

def seg_depart(sentence):
    # 对文档中的每一行进行中文分词
    # print("正在分词")
    sentence_depart = jieba.cut(str(sentence).strip())
    # 创建一个停用词列表
    stopwords = stopwordslist()
    # 输出结果为outstr
    outstr = ''
    # 去停用词
    for word in sentence_depart:
        if word not in stopwords:
            if word != '\t':
                outstr += word
                outstr += " "
    return outstr
def data_get():
    data_0 = pd.read_csv("体育.csv")
    data_1 = pd.read_csv("彩票.csv")
    data_2 = pd.read_csv("房产.csv")
    data_3 = pd.read_csv("时政.csv")
    data_4 = pd.read_csv("社会.csv")
    data_5 = pd.read_csv("股票.csv")
    data_6 = pd.read_csv("财经.csv")
    data = pd.concat([data_0, data_1, data_2, data_3, data_4, data_5, data_6]).reset_index(drop = True)
    return data

def train():
    x_train,x_test,y_train,y_test = train_test_split(seg_depart(data['text']), data.class_name, test_size=0.2, random_state=2020)

    pipe = Pipeline([('vect', CountVectorizer()),
                     ('tfidf', TfidfTransformer(binary=True)),
                     ('model', LogisticRegression())])

    model = pipe.fit(x_train, y_train)
    prediction = model.predict(x_test)
    print("accuracy: {}%".format(round(accuracy_score(y_test, prediction)*100,2)))

In [6]:
data = data_get()

In [7]:
newData = pd.Series(len(data.text))

In [9]:
for i in tqdm(range(len(data.text))):
        newData[i] = seg_depart(data.text[i])

  0%|          | 388/126920 [00:06<34:07, 61.80it/s]


KeyboardInterrupt: 

In [10]:
 x_train, x_test, y_train, y_test = train_test_split(newData, data.class_name, test_size=0.2,
                                                        random_state=2020)

ValueError: Found input variables with inconsistent numbers of samples: [4139, 126920]

In [1]:
from sklearn.neighbors import KNeighborsClassifier
pipe = Pipeline([('vect', CountVectorizer()),
                     
                     ('model', KNeighborsClassifier(n_neighbors = 10,weights = 'distance',algorithm = 'brute'))])

model = pipe.fit(x_train, y_train)

NameError: name 'Pipeline' is not defined

In [39]:
prediction = model.predict(x_test)
print("accuracy: {}%".format(round(accuracy_score(y_test, prediction) * 100, 2)))
print(confusion_matrix(y_test, prediction))
print(classification_report(y_test, prediction))

accuracy: 91.52%
[[3675   14    2   10   17   21    2]
 [  17 1428    0    4   23    4    3]
 [   8    2 3829   91   72   49   22]
 [  28    4   53 4089  106  200   55]
 [  59   22   88  359 3417   59   78]
 [  15    1   25  171   29 4148  131]
 [   4    2   45   57   40  160 2646]]
              precision    recall  f1-score   support

          体育       0.97      0.98      0.97      3741
          彩票       0.97      0.97      0.97      1479
          房产       0.95      0.94      0.94      4073
          时政       0.86      0.90      0.88      4535
          社会       0.92      0.84      0.88      4082
          股票       0.89      0.92      0.91      4520
          财经       0.90      0.90      0.90      2954

    accuracy                           0.92     25384
   macro avg       0.92      0.92      0.92     25384
weighted avg       0.92      0.92      0.92     25384

